config/routes.rb
Rails.application.routes.draw do
  get '/', { to: "home#index", as: "root" }
  get '/about', to: "about#index"
  resources :contacts, only: [:index, :new, :create]
  resources :products do
    resources :reviews, only: [:create, :destroy]
  end
  get '/signup', to: "users#new"
  post '/users', to: "users#create"
  resource :session, only: [ :create, :destroy]
  get '/login', to: "sessions#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/news_article.rb
class NewsArticle < ApplicationRecord
    validates :title, presence: true, uniqueness: { case_sensitive: false }
    validates :description, presence: true

end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :user
    has_many :reviews, dependent: :destroy
    before_validation :set_default_price

    validates(
        :title,
        presence: true,
        uniqueness: { case_sensitive: false }
    )

    validates(
        :description,
        presence: true,
        length: { minimum: 8 }
    )

    validates :price, numericality: { greater_than: 0 }

    before_validation :set_default_price
    before_validation :capitalize_title

    scope(:search, ->(query) { where("title ILIKE ? OR description ILIKE ?", "%#{query}%", "%#{query}%" )})

    private

    def set_default_price
        self.price ||= 1
    end

    def capitalize_title
        self.title.capitalize!
    end

end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :user
    belongs_to :product

    validates(
        :rating,
        presence: true,
        numericality: { 
            greater_than_or_equal_to: 1, 
            less_than_or_equal_to: 5
        }
    )
end

app/models/user.rb
class User < ApplicationRecord
    has_many :products, dependent: :nullify
    has_many :reviews, dependent: :nullify
    has_secure_password

    validates(:first_name, presence: true)
    validates(:last_name, presence: true)
    validates(:password_digest, presence: true)

    validates(
        :email, 
        presence: true, 
        uniqueness: true,
        format: /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
    ) 
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    private

    def current_user
        if session[:user_id].present?
            @current_user ||= User.find_by(id: session[:user_id])
        end
    end

    helper_method :current_user

    def user_signed_in?
        current_user.present?
    end
    
    helper_method :user_signed_in?

    def authenticate_user!
        unless user_signed_in?
            flash[:danger] = "You must sign in or sign up first!"
            redirect_to login_path
        end
    end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
    def index
    end

    def create
        @name = params[:name]
        @email = params[:email]
        @text = params[:text]
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    def index
    end
    
    def new
    end

    def create
        @name = params[:name]
        @email = params[:email]
        @body = params[:body]
        redirect_to contacts_path
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :find_product, only: [:show, :edit, :update, :destroy]

    def index 
        @products = Product.all.order(created_at: :asc)
    end

    def new
        @product = Product.new
    end

    def create 
        @product = Product.new product_params
        @product.user = current_user
        if @product.save
            flash[:primary] = "Created product \"#{@product.title}\""
            redirect_to product_path(@product)
        else
            flash[:danger] = @product.errors.full_messages.join(', ')
            render :new
        end
    end

    def show
        @review = Review.new
        @reviews = @product.reviews.order(created_at: :desc) 
    end

    def edit
    end

    def update
        if @product.update product_params
            flash[:primary] = "#{@product.title} was updated"
        else
            flash[:danger] = @product.errors.full_messages.join(', ')
        end
        redirect_to product_path(@product)
    end

    def destroy
        @product.destroy
        redirect_to products_path
    end

    private 

    def find_product
        @product = Product.find(params[:id])
    end

    def product_params
        params.require(:product).permit(:title, :description, :price)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :authenticate_user!

    def create 
        @product = Product.find(params[:product_id])
        @review = Review.new params.require(:review).permit(:rating, :body)
        @review.product = @product
        @review.user = current_user
        if @review.save
            flash[:primary] = "Review saved"
            redirect_to @product
        else
            flash[:danger] = @review.errors.full_messages.join(', ')
            @reviews = @product.reviews.order(created_at: :desc)
            render 'products/show'
        end
    end

    def destroy
        @review = Review.find(params[:id])
        if @review.destroy
            flash[:primary] = "Review deleted"
            redirect_to product_path(@review.product)
        else
            head :unauthorized
        end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        user = User.find_by_email params[:email]
        if user&.authenticate params[:password]
            session[:user_id] = user.id
            redirect_to root_path, notice: 'Logged in'
        else
            flash[:alert] = "Wrong email or password"
            render :new
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:notice] = 'Logged out'
        redirect_to root_path 
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new user_params
        if @user.save
            session[:user_id] = @user.id
            redirect_to root_path
        else
            flash[:danger] = @user.errors.full_messages.join(', ')
            render :new
        end
    end

    private

    def user_params
       params.require(:user).permit(
           :first_name, 
           :last_name, 
           :email, 
           :password, 
           :password_confirmation
        )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h1>About Amazon</h1>

app/views/contact/new.html.erb
<div class="container">
<h1>Contact Us</h1>
<%= form_with url: new_contact_path, local: true do |f| %>
  <div>
    <%= f.label :subject %>
    <%= f.text_field :subject %>
  </div>
  <div>
    <%= f.label :message %>
    <%= f.text_area :message %>
  </div>
  <%= f.submit %>
    <% end %>
    </div>

app/views/contacts/index.html.erb
<h1>Thank you for contacting us!</h1>

app/views/contacts/new.html.erb
<h1>Contact Us</h1>
<%= form_tag contacts_path do %>
<div>
    <%= label_tag :name %>
    <%= text_field_tag :name %>
</div>
<div>
    <%= label_tag :email %>
    <%= email_field_tag :email %>
</div>
<div>
    <%= label_tag :body %>
    <%= text_area_tag :body %>
</div>
<%= submit_tag "Submit" %>
<% end %>

app/views/home/about.html.erb
<p>Amazon.com, Inc.[6] (/ˈæməˌzɒn/), is an American multinational technology company based in Seattle, Washington that focuses in e-commerce, cloud computing, and artificial intelligence.

Amazon is the largest e-commerce marketplace and cloud computing platform in the world as measured by revenue and market capitalization.[7] Amazon.com was founded by Jeff Bezos on July 5, 1994, and started as an online bookstore but later diversified to sell video downloads/streaming, MP3 downloads/streaming, audiobook downloads/streaming, software, video games, electronics, apparel, furniture, food, toys, and jewelry. The company also owns a publishing arm, Amazon Publishing, a film and television studio, Amazon Studios, produces consumer electronics lines including Kindle e-readers, Fire tablets, Fire TV, and Echo devices, and is the world's largest provider of cloud infrastructure services (IaaS and PaaS) through its AWS subsidiary.[8] Amazon has separate retail websites for some countries and also offers international shipping of some of its products to certain other countries.[9] 100 million people subscribe to Amazon Prime.[10][11]

Amazon is the largest Internet company by revenue in the world[12] and the second largest employer in the United States.[13] In 2015, Amazon surpassed Walmart as the most valuable retailer in the United States by market capitalization.[14] In 2017, Amazon acquired Whole Foods Market for $13.4 billion, which vastly increased Amazon's presence as a brick-and-mortar retailer.[15] The acquisition was interpreted by some[by whom?] as a direct attempt to challenge Walmart's traditional retail stores.</p>

app/views/home/index.html.erb
<h1>Home</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Amazon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav>
      <%= link_to 'Home', root_path %>
      |
      <%= link_to 'About', about_path %>
      |
      <%= link_to 'Contact Us', new_contact_path %>
      |
      <%= link_to 'Products', products_path %>
      |
      <%= link_to 'New Product', new_product_path %>
      <% if user_signed_in? %>
      |
      <span>Logged in as: <%= current_user.first_name %></span>
      |
      <%= 
        link_to 'Sign Out', 
        session_path, 
        method: :delete, 
        data: { confirm: "Log out?"}
      %>
      <% else %>
      <%= link_to 'Login', login_path %>
      |
      <%= link_to 'Sign Up', signup_path %>
      <% end %>
    </nav>
    <% flash.each do |type, message| %>
          <div>
            <%= message %>
          </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with model: @product, local: true do |f| %>
<div>
    <%= f.label :title %>
    <%= f.text_field :title %>
</div>
<div>
    <%= f.label :description %>
    <%= f.text_area :description %>
</div>
<div>
    <%= f.label :price %>
    <%= f.number_field :price %>
</div>
<%= f.submit %>
<% end %>

app/views/products/edit.html.erb
<h1>Edit <%= @product.title %></h1>

<%= render "form" %>

<%= link_to 'Cancel', product_path(@product) %>

app/views/products/index.html.erb
<h1>Our Products</h1>
<%= @products.each do |product| %>
    <h2><%= link_to product.title, product_path(product) %></h2>
    <p><%= product.description %></p>
    <p><%= number_to_currency product.price %></p>
    <p>Created by: <%= product.user&.first_name || "Deleted"%></p>
    <hr>
<% end %>

app/views/products/new.html.erb
<h1>New Product</h1>
<%= render "form" %>
<%= link_to 'Cancel', products_path %>

app/views/products/show.html.erb
<h1><%= @product.title %></h1>
<p><%= @product.description %></p>
<p><%= number_to_currency @product.price %></p>
<p>Created by: <%= @product.user&.first_name || "Deleted" %></p>
<%= link_to 'Edit', edit_product_path(@product) %>
|
<%= 
    link_to 'Delete', 
    product_path(@product), 
    method: :delete,
    data: { confirm: "Are you sure you want to delete #{@product.title}?" }
%>
<h2>Reviews</h2>
<% @reviews.each do |review| %>
    <p><%= review.rating %> out of 5</p>
    <p><%= review.body %></p>
    <p>
        Posted by 
        <%= review.user&.first_name || "Deleted" %> on 
        <%= review.created_at.strftime "%b %d, %Y" %>
    </p>
    <%=
        link_to 'Delete',
        product_review_path(@product, review), 
        method: :delete, 
        data: {
            confirm: "Are you sure you want to delete review?"
        }
    %>
<% end %>
<h4>Write a Review</h4>
<%= form_with model: [@product, @review], local: true do |f| %>
<div>
    <%= f.label :rating %>
    <%= f.number_field :rating %>
</div>
<div>
    <%= f.label :body %>
    <%= f.text_area :body %>
</div>
<%= f.submit "Write Review" %>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_with model: @user, local: true do |f| %>
    <div>
        <%= f.label :first_name %>
        <%= f.text_field :first_name %>
    </div>
    <div>
        <%= f.label :last_name %>
        <%= f.text_field :last_name %>
    </div>
    <div>
        <%= f.label :email %>
        <%= f.email_field :email %>
    </div>
    <div>
        <%= f.label :password %>
        <%= f.password_field :password %>
    </div>
    <div>
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %>
    </div>
        <%= f.submit "Sign Up" %>
<% end %>